name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASS: ${{ secrets.PASSWORD }}
      PASS2: ${{ secrets.PASSWORD2 }}
    steps:
      - run: echo "${PASS}"
      - run: echo "${PASS2:0:1} ${PASS2#?}"
